language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: LP7v7nS1Nd08J1Gg8Kl0FsPRG6MCCG6LyNU4lGk4gl47GKD20cE9yPA+dwUlstyajmbrVrK7lt+wQN+WkcO4G6GvqPZ5qA8dXxF66az0SEIgqsAQ2KIvGDLYoSNFJ6N89I/Fvb44rd/7g5smQtDqPpjemmk2JDc3eZ6c8f4lpCBguJ/mcJtiQBuHHpxGUNf1jbK4D0fEvyUwGbNQugkgeujgNjSSVLnMyXm68/6d06MXJQbtRYam4baiH1p5OhMafhpqfL79YyP8pp5BlIKbhTaeRU5LpkteaPKgBwrl4bfyfv9kvOPdInEfG/ufc+PiLcVLJM1sE04zliGAR899VvO5kNhvK1+2sT/WKn/nC3++N6UyAfVYn40TkpqVHMIo5XSVtp28EWcwjudDCHHgOrWGn3K0pAg40I6aEzvYHD5rxCev01JffLoBWIr8VuHWgVTjA+40vO4lNpf1dXcdQHmFM3h3BgHalPusuMypW9meo/ZACebnZW3k9+lS5qgWqsfbKpVk+qOlsnRsXhKfQ29M9QmAuopErKB/UB2cUufMfKI8c9LgMa9+G73m0sr5kMxdkN0xWcfrb6VjnLjmL2m8MVY9uLC1f8RDitja7/bpkkwpXvjOmawOCZ0A2xnPt1lL8QAZkFmtxva6AxL7XS63LochkCAZGfS+y5KEEEY=
  app: glacial-depths-39608
  on:
    repo: RobertVFrazier/Blog-App-Mongoose-Test-Challege
